# Generated by Django 4.2.7 on 2025-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalpark',
            name='entry_fee_citizen',
        ),
        migrations.RemoveField(
            model_name='nationalpark',
            name='entry_fee_non_resident',
        ),
        migrations.RemoveField(
            model_name='nationalpark',
            name='entry_fee_resident',
        ),
        migrations.AlterField(
            model_name='wildlife',
            name='parks',
            field=models.ManyToManyField(related_name='wildlife', to='parks.nationalpark'),
        ),
    ]
