# Generated by Django 4.2.7 on 2025-08-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('site_type', models.CharField(choices=[('archaeological', 'Archaeological Site'), ('cultural', 'Cultural Heritage Site'), ('colonial', 'Colonial Heritage'), ('religious', 'Religious Site'), ('museum', 'Museum'), ('monument', 'Monument')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=300)),
                ('historical_significance', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('visiting_hours', models.CharField(blank=True, max_length=100)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('best_time_to_visit', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='historical_sites/')),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historical Site',
                'verbose_name_plural': 'Historical Sites',
                'db_table': 'core_historicalsite',
                'ordering': ['name'],
            },
        ),
    ]
