# Generated by Django 4.2.7 on 2025-08-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_budget',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_luxury',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_standard',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='single_supplement_budget',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='single_supplement_luxury',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='single_supplement_standard',
        ),
    ]
