# Generated by Django 4.2.7 on 2025-08-20 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tourpackage_price_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touravailability',
            name='booked_participants',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='touravailability',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Leave blank for unlimited participants', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='max_group_size',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Leave blank for unlimited participants', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tourpackageextra',
            name='advance_booking_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tourpackageextra',
            name='max_quantity_per_booking',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
