# Generated by Django 4.2.7 on 2025-08-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('cash', 'Cash Payment'), ('cash_on_arrival', 'Cash on Arrival')], max_length=20),
        ),
    ]
