# Generated by Django 4.2.7 on 2025-08-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingpayment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
